stop the build when gcloud command failed

diff --git a/osconfig-packagebuild-cloudbuild.yaml b/osconfig-packagebuild-cloudbuild.yaml
--- a/osconfig-packagebuild-cloudbuild.yaml
+++ b/osconfig-packagebuild-cloudbuild.yaml
@@ -31,7 +31,7 @@ substitutions:
   _REPO_NAME: 'osconfig'
   _GIT_REF: 'a361f8114fbfbaea8b48042a76726162ec8bf2be'
   _GCS_PATH: 'gs://mahmoudn-image-import-bucket/osconfig-packages-testing'
-  _VERSION: '20240103.01'
+  _VERSION: '20240103.02'
   _DAISY_WORKFLOW: '/workspace/packagebuild/workflows/build_deb10.wf.json'
   _DAISY_DOCKER_TAG: 'latest'
   _SBOM_UTIL_GCS_ROOT: 'gs://mahmoudn-image-import-bucket/osconfig-packages-testing'
@@ -81,12 +81,21 @@ steps:
     REGIONS=()
     readarray -t REGIONS < ./supported-regions
 
+    exit_on_error() {
+      ERR=$$1
+      if [[ $$ERR != 0 ]]; then
+      echo "Deploy failed with exit code $$ERR. Please check the error message, debug and rerun."
+      exit "$$ERR"
+      fi
+    }
+
+
     for _REGION in ${REGIONS[@]}
       do
         echo "--> Deploying... osconfig agent package -> $$_REGION in $$_PROJECT project."
 
-        gcloud artifacts apt import osconfig-agent-test --location=$$_REGION --project=${_BUILDER_PROJECT} --gcs-source=gs://mahmoudn-image-import-bucket/osconfig-packages-testing/*
-
+        gcloud artifacts apt import osconfig-agent-test --location=$$_REGION --project=${_BUILDER_PROJECT} --gcs-source=gs://mahmoudn-image-import-bucket/osconfig-packages-testing/*  -q
+        exit_on_error $$?
       done
     echo "----> Deployed osconfig agent package for all regions in $$_PROJECT project"
 
